import Head from 'next/head'
import { useRouter } from 'next/router'

import { Space, Typography } from 'antd'

import Layout from 'components/Layout/Layout'
import QuestionsBlock from 'components/QuestionsBlock/QuestionsBlock'

import { topics } from 'data/topics'

export default function Topic() {
  const { query } = useRouter()

  const topicId = query.id as string

  const topic = topics.find((t) => t.id === topicId)

  const questions = topic?.questions

  if (!topic) {
    return null
  }

  return (
    <Layout>
      <Head>
        <title>{topic.name}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Space direction='vertical' style={{ width: '100%' }}>
          <Typography.Title level={4}>{topic.name}</Typography.Title>

          {questions && <QuestionsBlock questions={questions} />}
        </Space>
      </main>
    </Layout>
  )
}
