import Head from 'next/head'

import { Space, Typography, Collapse, List, Divider } from 'antd'

import Layout from 'components/Layout/Layout'

import styles from '../Topic.module.css'

export default function Estimations() {
  return (
    <Layout>
      <Head>
        <title>Estimatimations</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Space direction='vertical' className={styles.rootCard}>
          <Typography.Title level={3}>Estimatimations</Typography.Title>
          <Divider orientation='left' dashed={true}>
            Story Point
          </Divider>
          <Typography.Text>
            Story point is relative measurement of difficulty of task and agreed
            within team. Usually, people use fibonacci number for story points.
            After few iterations estimation within team getting more aligned and
            accurate. Unlike hours, the difficulty is team based, but different
            members can fulfil that estimations within different timeframe.
          </Typography.Text>
          <Divider orientation='left' dashed={true}>
            Velocity
          </Divider>
          <Typography.Text>
            Story point allows us to track velocity, how many story points team
            can delivery within the sprint. And after collection statistics for
            last few sprint(4-6), we can predict our sprint-capacity
          </Typography.Text>
          <Divider orientation='left' dashed={true}>
            Estimation techniques
          </Divider>
          <Collapse>
            <Collapse.Panel header='Planning Poker' key='poker'>
              Everyone selects card, that represents his opinion. Then all cards
              reveiled, and people from lowest and higher estimate explain their
              opinion. After that people revote, until we have equal estimate.
            </Collapse.Panel>
            <Collapse.Panel header='T-shirt sizing' key='t-shirt'>
              T-shirt sizing is a technique for estimating big epics without
              diving into big details. We estimate stories in sprints.
            </Collapse.Panel>
            <Collapse.Panel header='3-point estimate' key='3-point'>
              We gives estimates in 3 way. Worst case/Best case/Average case.
              Then we take average value among these three and consider it to be
              our estimate.
            </Collapse.Panel>
            <Collapse.Panel header='Top-down' key='top-bottom'>
              In this strategy we have limited budget and we look at overall
              project and highlighted certain significant parts of it. What we
              are trying to do is understand whether project is viable or not.
            </Collapse.Panel>
            <Collapse.Panel header='Bottom-up' key='bottom-up'>
              In this strategy we are look from practical level, from each
              individual task and elements that defined in the scope. What we
              are trying to do is calculate overall cost of the project.
            </Collapse.Panel>
          </Collapse>
          <Divider orientation='left' dashed={true}>
            Participation
          </Divider>
          <Typography.Text>
            Developers and testers should participate in estimations, every
            person might have concerns and would help us to be more accurate.
            New members also should be involved in estimatiosn as soon as
            possible, even though their knowledge is limited. In this way they
            will learn to estimate faster.
          </Typography.Text>
          <Typography.Text>
            Single person estimate might not be that accurate and in this
            approach we are missing knowledge sharing. And if that only person
            is sick and left team, then there will be no replacement.
          </Typography.Text>
          <Divider orientation='left' dashed={true}>
            Unknown scope
          </Divider>
          <Typography.Text>
            We need to split scope into stages and use non-accurate estimation
            techniques considering risks.
          </Typography.Text>
          <Divider orientation='left' dashed={true}>
            Risks
          </Divider>
          <List bordered={true}>
            <List.Item>Underestimated tasks</List.Item>
            <List.Item>Overestimated team velocity</List.Item>
            <List.Item>
              Additional requirements(e.g. new stories, bugs, changed scope)
            </List.Item>
            <List.Item>Illnesses</List.Item>
            <List.Item>Dependecies</List.Item>
            <List.Item>Inefficient communication within/outside team</List.Item>
          </List>
          <Typography.Text>
            In order to deal with this risks, we should agree with customer
            about risk multiplier, which can be updated during future
            development
          </Typography.Text>
          <Divider orientation='left' dashed={true}>
            Handling estimation failures
          </Divider>
          <Typography.Text>
            We need to understand reasons of the failures and take them into
            consideration in following spints. We also need to be able to
            explain to customer those reasons
          </Typography.Text>
          <Typography.Text>
            In case we about to fail fulfilment of the sprint scope, we should
            notify customer about it as soon as possible, so that they will be
            able adapt to it.
          </Typography.Text>
          <Typography.Text>
            In case we already failed, we need to reestimate remaning features
            and let customer prioritise them.
          </Typography.Text>
        </Space>
      </main>
    </Layout>
  )
}
